# **Data Cleaning in Python**

In [3]:
# @title
# Magic Command
# Print multiple statements in same line
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
# @title
import seaborn as sns
# Load the Titanic Data set
df=sns.load_dataset('titanic')

# Step 1:  KNOW YOUR DATA FIRST
Understand the structure, data types, and overall distribution of your dataset before making changes.

# WHEN TO USE
Start here - before cleaning, transforming, or modeling

# QUICK CHECKS
df.head()
df.info()
df.describe()

In [5]:
# @title
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [18]:
# @title
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     891 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(6)
memory usage: 86.6+ KB

In [7]:
# @title
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

# Step 2 STANDARDIZE YOUR DATA
Keep text, dates, and categories in a consistent format across the dataset.

# WHEN TO USE
When data is collected from forms, users, or different sources.

# EXAMPLE
df['class'] = df['class'].str.strip().str.lower()

In [8]:
# @title
print("Before converting class column to lower case")
df.head()
df['class'] = df['class'].str.strip().str.lower()
print("After converting class column to lower case")
df.head()

Before converting class column to lower case

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

After converting class column to lower case

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,first,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,first,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,third,man,True,NaN,Southampton,no,True

# Step 3 : DETECT MISSING DATA
Find out which values are empty or incomplete in your dataset.

# WHEN TO USE
Before analysis - nulls can break calculations and skew results.

# EXAMPLE
df.isna().sum()

# For better formatting headers
df.isna().sum().reset_index()

In [9]:
# @title

print ("Null values in the columns of the dataset")
nullcolValue = df.isna().sum()
nullcolValue
null_counts = df.isna().sum().reset_index()
null_counts.columns = ['Column Name', 'Total null values']
null_counts

Null values in the columns of the dataset

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

    Column Name  Total null values
0      survived                  0
1        pclass                  0
2           sex                  0
3           age                177
4         sibsp                  0
5         parch                  0
6          fare                  0
7      embarked                  2
8         class                  0
9           who                  0
10   adult_male                  0
11         deck                688
12  embark_town                  2
13        alive                  0
14        alone                  0

# Step 4 : TREAT MISSING VALUES
Choose whether to remove gaps or replace them with meaningful values.

# WHEN TO USE
If nulls are affecting calculations, models, or reports.

# EXAMPLE
df['age'].fillna(df['age'].median(),inplace=True)
df['embarked'].fillna(df['embarked'].mode()[0],inplace=True)

![image.png](attachment:image.png)

In [17]:
# @title
df['age'].fillna(df['age'].median(),inplace=True)
# When you use inplace=True: Direct Modification: Pandas goes into the memory where df['age'] is stored
# and updates the values right there.
# inplace=False (Default) A new Series/DataFrame with the fix
df['embarked'].fillna(df['embarked'].mode()[0],inplace=True)

/tmp/ipython-input-4178930036.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(),inplace=True)

In [11]:
# @title
# Check randomly 10 rows
df.sample(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
640,0,3,male,20.0,0,0,7.8542,S,third,man,True,NaN,Southampton,no,True
209,1,1,male,40.0,0,0,31.0000,C,first,man,True,A,Cherbourg,yes,True
601,0,3,male,28.0,0,0,7.8958,S,third,man,True,NaN,Southampton,no,True
577,1,1,female,39.0,1,0,55.9000,S,first,woman,False,E,Southampton,yes,False
763,1,1,female,36.0,1,2,120.0000,S,first,woman,False,B,Southampton,yes,False
719,0,3,male,33.0,0,0,7.7750,S,third,man,True,NaN,Southampton,no,True
391,1,3,male,21.0,0,0,7.7958,S,third,man,True,NaN,Southampton,yes,True
602,0,1,male,28.0,0,0,42.4000,S,first,man,True,NaN,Southampton,no,True
384,0,3,male,28.0,0,0,7.8958,S,third,man,True,NaN,Southampton,no,True
214,0,3,male,28.0,1,0,7.7500,Q,third,man,True,NaN,Queenstown,no,False

# Step : 5 DETECT DUPLICATE RECORDS
Find rows that appear more than once in your dataset.

# WHEN TO USE
Counts look inflated or after merging multiple files
# EXAMPLE

df.duplicated().sum()

In [15]:
# @title
df.shape
duplicate_count = df.duplicated().sum()
print(f"Total Duplicate Rows: {duplicate_count}")

(891, 15)

Total Duplicate Rows: 110

In [14]:
# @title
# Show the duplicates AND their original counterparts
all_duplicates = df[df.duplicated(keep=False)]
print(all_duplicates.sort_values(by=list(df.columns)))

     survived  pclass   sex   age  sibsp  parch     fare embarked   class  \
64          0       1  male  28.0      0      0  27.7208        C   first
295         0       1  male  28.0      0      0  27.7208        C   first
144         0       2  male  18.0      0      0  11.5000        S  second
757         0       2  male  18.0      0      0  11.5000        S  second
658         0       2  male  23.0      0      0  13.0000        S  second
..        ...     ...   ...   ...    ...    ...      ...      ...     ...
692         1       3  male  28.0      0      0  56.4958        S   third
65          1       3  male  28.0      1      1  15.2458        C   third
709         1       3  male  28.0      1      1  15.2458        C   third
74          1       3  male  32.0      0      0  56.4958        S   third
838         1       3  male  32.0      0      0  56.4958        S   third

     who  adult_male deck  embark_town alive  alone
64   man        True  NaN    Cherbourg    no   True
295  man        True  NaN    Cherbourg    no   True
144  man        True  NaN  Southampton    no   True
757  man        True  NaN  Southampton    no   True
658  man        True  NaN  Southampton    no   True
..   ...         ...  ...          ...   ...    ...
692  man        True  NaN  Southampton   yes   True
65   man        True  NaN    Cherbourg   yes  False
709  man        True  NaN    Cherbourg   yes  False
74   man        True  NaN  Southampton   yes   True
838  man        True  NaN  Southampton   yes   True

[163 rows x 15 columns]